# Generated by Django 3.2.14 on 2024-11-13 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cupboard_app', '0002_customingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='customingredient',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='cupboard_app.user'
            ),
            preserve_default=False,
        ),
    ]
