# Generated by Django 3.2.14 on 2024-11-26 06:35

from django.db import migrations


def change_list_ingredients_format(apps, schema_editor):
    UserListIngredients = apps.get_model('cupboard_app', 'UserListIngredients')
    for list in UserListIngredients.objects.all():
        new_ingredients = []
        for ingredient in list.ingredients:
            new_ingredient = {
                'ingredient_name': ingredient.get('ingredient_name'),
                'ingredient_type': ingredient.get('ingredient_type'),
                'amount': ingredient.get('amount'),
                'unit': ingredient.get('unit'),
                'is_custom_ingredient': ingredient.get('is_custom_ingredient', False)
            }
            new_ingredients.append(new_ingredient)
        list.ingredients = new_ingredients
        list.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cupboard_app', '0002_customingredient'),
    ]

    operations = [
        # migrations.RunPython.noop is basically doing nothing if we have to downgrade
        migrations.RunPython(change_list_ingredients_format, migrations.RunPython.noop)
    ]
