name: backend_ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
	        ref: main

      - run: echo "Hello World!"