name: backend_ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  env_file: ${{ secrets.env }}
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python -m venv venv
          echo "$env_file" > ".env"
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pyopenssl --upgrade
          flake8
