name: backend_cd

on:
  workflow_dispatch:

env:
  env_file: ${{ secrets.ENV_PROD }}
  aws_pem_file: ${{ secrets.AWS_PEM_FILE }}

jobs:
  build-and-share:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy aws.pem and .env
        run: |
          echo "$env_file" > ".env"
          echo "$aws_pem_file" > aws.pem
          chmod 600 aws.pem

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:latest
