name: backend_ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - run: pip install -r requirements.txt
      - run: pip install pyopenssl --upgrade
      - env:
          env_file: ${{ secrets.env }}
        run: echo "$env_file" > ".env"
      - run: echo .env
      - run: python manage.py test
