name: backend_ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - run: python -m venv testVenv
      - run: cd testVenv/Scripts
      - run: ls
      - run: cd ..
      - run: cd ..
      - run: source testVenv/Scripts/activate.ps1
      - run: pip install -r requirements.txt
      - run: pip install pyopenssl --upgrade
      - run: pip install --force-reinstall -v "cryptography==42.0.0"
      - env:
          env_file: ${{ secrets.env }}
        run: echo "$env_file" > ".env"
      - run: python manage.py test
