name: backend_cd

on:
  workflow_dispatch:

env:
  env_file: ${{ secrets.env_prod }}
  aws_pem_file: ${{ secrets.aws_pem_file }}
  docker_password: ${{ secrets.docker_password }}
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main 
      - uses: actions/checkout@v4
        with:
          ref: Jethro/Com-160/Docker_Pipeline_Prep
      - run: ls && echo "$env_file" > ".env" && echo "$aws_pem_file" > aws.pem && docker login --username swanso15 --password $docker_password && docker build -t swanso15/cupboard_backend:latest . && docker image ls && docker save -o cupboard_backend.tar swanso15/cupboard_backend:latest
